[rs-infra-style]
source = "https://github.com/qubit-ltd/rs-infra-style.git"
revision = "8c9a9ce043871767900fa3a4ee5b5b4c6c0f1a7f"
binary = "rs-infra-style"
package = "qubit-infra-style"

[rs-infra-verify]
source = "https://github.com/qubit-ltd/rs-infra-verify.git"
revision = "c01e036da6e367b3adcc7f40c3c39134baaeecca"
binary = "rs-infra-verify"
package = "qubit-infra-verify"

[rs-infra-coverage]
source = "https://github.com/qubit-ltd/rs-infra-coverage.git"
revision = "9cd9514b3254257cd05a02c03e7d579b67d1d0fb"
binary = "rs-infra-coverage"
package = "qubit-infra-coverage"

[rs-infra-pages]
source = "https://github.com/qubit-ltd/rs-infra-pages.git"
revision = "d8057d937294edcb456e40d6768c87f3a5b7c815"
binary = "rs-infra-pages"
package = "qubit-infra-pages"

[rs-infra-ci]
source = "https://github.com/qubit-ltd/rs-infra-ci.git"
revision = "1c1187c15d0bd15d90688f25d7aceef65a91be03"
binary = "rs-infra-ci"
package = "qubit-infra-ci"

[rs-infra-dependency]
source = "https://github.com/qubit-ltd/rs-infra-dependency.git"
revision = "1239fb3f7d7c65b989d98b3a4a4fd8bc01c6c1f2"
binary = "rs-infra-dependency"
package = "qubit-infra-dependency"
