[rs-infra-style]
source = "https://github.com/qubit-ltd/rs-infra-style.git"
revision = "5e96f066cea9536e99bd5b4227b5ba0488c96581"
binary = "rs-infra-style"
package = "qubit-infra-style"

[rs-infra-verify]
source = "https://github.com/qubit-ltd/rs-infra-verify.git"
revision = "468368033249d703ec98588f93cc39cbbb7dcb6b"
binary = "rs-infra-verify"
package = "qubit-infra-verify"

[rs-infra-coverage]
source = "https://github.com/qubit-ltd/rs-infra-coverage.git"
revision = "36dc056af442ea5a8aa8e04719218ba03f2b3bb2"
binary = "rs-infra-coverage"
package = "qubit-infra-coverage"

[rs-infra-pages]
source = "https://github.com/qubit-ltd/rs-infra-pages.git"
revision = "aa6a9663bc76d9e52beea1dea4a06f1c45523179"
binary = "rs-infra-pages"
package = "qubit-infra-pages"

[rs-infra-ci]
source = "https://github.com/qubit-ltd/rs-infra-ci.git"
revision = "98463821cf1898dfa6468b4af8edd20e943406a0"
binary = "rs-infra-ci"
package = "qubit-infra-ci"

[rs-infra-dependency]
source = "https://github.com/qubit-ltd/rs-infra-dependency.git"
revision = "dc7539a62b22941ea86aec1b88be9a09e79d09c9"
binary = "rs-infra-dependency"
package = "qubit-infra-dependency"
